python_sources(name="tests")
python_tests(
    name="test",
    dependencies=[
        "//:root#aws-cdk-lib",
        "//:root#constructs",
    ],
)

python_test_utils(
    name="test_utils",
    dependencies=[
        "//:root#aws-cdk-lib",
        "//:root#constructs",
    ],
)
